# Site settings
# accessible in the templates via {{ site.myvariable }}.

title: ±
tagline: The terrifying machine
baseurl: ""
url: "https://ck.is-a.dev"

timezone: Etc/UTC
permalink: /:title

paginate_path: /posts/:num/
paginate: 5

collections:
  - cats

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /article/:title

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
